// Generated by CoffeeScript 1.6.2
(function () {
  var query_absence;

  $(function () {
    $("#absence a[target='query']").click(function (e) {
      e.preventDefault();
      return query_absence();
    });
    $("#absence ul[target='semester-options'] a").click(function (e) {
      e.preventDefault();
      $("#absence span[target='semester']").html($(this).html());
      return $("#absence span[target='semester']").attr("value", $(this).attr("value"));
    });
    return gadget.getContract("emba.student").send({
      service: "default.GetSemester",
      body: "",
      result: function (response, error, http) {
        var semester;

        $("#absence input[target='schoolYear']").val(response.Result.SystemConfig.DefaultSchoolYear);
        semester = response.Result.SystemConfig.DefaultSemester;
        $("#absence span[target='semester']").attr("value", semester);
        if (semester === "0") {
          semester = "夏季學期";
        }
        if (semester === "1") {
          semester = "第 1 學期";
        }
        if (semester === "2") {
          semester = "第 2 學期";
        }
        return $("#absence span[target='semester']").html(semester);
      }
    });
  });

  query_absence = function () {
    return gadget.getContract("emba.student").send({
      service: "default.GetAbsence",
      body: {
        Request: {
          SchoolYear: $("#absence input[target='schoolYear']").val(),
          Semester: $("#absence span[target='semester']").attr("value")
        }
      },
      result: function (response, error, http) {
        var items;

        items = [];
        if (response.Result != null) {
          $(response.Result.Absence).each(function (index, item) {
            return items.push(`
              <div class="dis-show">
                <div class="bd-callout px-4 pt-3 requiredt">
                  <div class="card text-muted cursor-pointer collapsed" aria-expanded="false" data-toggle="collapse" data-target="#classlist${index}" aria-controls="classlist${index}">
                    <div class="flex justify-center items-center gap-x-2 pb-3">
                      <div></div>
                      <div class="flex flex-col">
                        <div class="text-base font-semibold requiredt">${item.CourseName}</div>
                        <div class="whitespace-pre-line">${(item.StartTime.substr(0, 10))} ( ${(item.StartTime.substr(11, 5))} - ${(item.EndTime.substr(11, 5))} )</div>
                      </div>
                      <div class="flex-grow text-xl text-right pr-2">
                        <i class="collapse-close fa fa-angle-down font-bold text-xl" aria-hidden="true"></i>
                        <i class="collapse-open fa fa-angle-up font-bold text-xl" aria-hidden="true"></i>
                      </div>
                    </div>
                  </div>
                  <div class="text-muted -mx-4 px-4 collapse" style="background: rgb(250, 250, 250)" id="classlist${index}" aria-expanded="false">
                    <hr class="mb-2 mt-0" />
                    <div class="flex justify-between mb-3">
                    <div class="text-center">
                      <div>課程識別碼</div>
                      <div class="font-bold">${item.SubjectCode}</div>
                    </div>
                      <div class="text-center">
                        <div>學年度</div>
                        <div class="font-bold">${item.SchoolYear}</div>
                      </div>
                      <div class="text-center">
                        <div>學期</div>
                        <div class="font-bold">${item.Semester === "0" ? "夏季學期" : "第" + item.Semester + "學期"}</div>
                      </div>
                    </div>
                    <hr class="my-2" />
                    <div>補課訊息</div>
                    <div class="font-bold pb-2">${item.MakeUpDescription}</div>
                    </div>
                  </div>
                </div>
              </div>
              <tr class="dis-none">
                <td>${item.SchoolYear}</td>
                <td>${item.Semester === "0" ? "夏季學期" : "第" + item.Semester + "學期"}</td>
                <td>${item.CourseName}</td>
                <td>${item.SubjectCode}</td>
                <td>${(item.StartTime.substr(0, 10))}</td>
                <td>${(item.StartTime.substr(11, 5))} - ${(item.EndTime.substr(11, 5))}</td>
                <td>${item.MakeUpDescription}</td>
              </tr>
                `);
          });
        }
        return $("#absence #absence-detail tbody").html((items.length === 0 ? '<tr><td colspan="7">無資料</td></tr>' : items.join("")));
      }
    });
  };

}).call(this);
