// Generated by https://quicktype.io

export interface MyInfo {
    name:        string;
    account:     string;
    language:    string;
    isTeacher:   boolean;
    isStudent:   boolean;
    isParent:    boolean;
    teacherId:   number;
    studentId:   number;
    child:       any[];
    application: Application[];
}

export interface Application {
    ap_name: string;
    name:    string;
}
